### ISSUE TITLE
Module reference error

### ISSUE THREAD

**Issue by Liang2580** [onlynishant/LuaFFIJson#1]
My nginx 1.16.1 references this module and directly reports the error information as follows:
loop or previous error loading module 'JsonParser'

**Comment by Liang2580** [comment]
It's all right to refer to FII

**Comment by onlynishant** [comment]
Hi @Liang2580 can you please post complete error/stack trace? Please check if you have placed  `JsonParser` module in correct lua package path.
reference: https://github.com/openresty/lua-nginx-module#lua_package_path
